package com.circadiandisplay.core.curve

/**
 * A named, ordered collection of [CurvePoint]s representing a full
 * evening adjustment schedule.
 *
 * Only one profile may be active at a time. The active profile is the
 * one used by the scheduler to evaluate display state.
 *
 * @property id        Primary key, auto-generated by Room.
 * @property name      User-defined display name. Must not be blank.
 * @property isActive  Whether this profile is the currently selected one.
 * @property createdAt Unix timestamp (ms) of creation, used for display ordering.
 */
data class CurveProfile(
    val id: Long = 0,
    val name: String,
    val isActive: Boolean = false,
    val createdAt: Long = System.currentTimeMillis(),
) {
    init {
        require(name.isNotBlank()) {
            "Profile name must not be blank"
        }
    }
}
