package com.circadiandisplay.core.curve

/**
 * A single node on a comfort curve.
 *
 * Each point defines the desired warmth and dimming at a specific
 * time of day. [CurveEngine] linearly interpolates between
 * consecutive points to produce a smooth transition.
 *
 * @property id          Primary key, auto-generated by Room.
 * @property profileId   Foreign key to the owning [CurveProfile].
 * @property timeMinutes Minutes since midnight. Range: `0–1439` (e.g., `1320` = 22:00).
 * @property warmth      Normalized warmth: `0.0` = no color shift, `1.0` = maximum warm.
 * @property dimming     Normalized dimming: `0.0` = no dimming, `1.0` = maximum dim.
 */
data class CurvePoint(
    val id: Long = 0,
    val profileId: Long = 0,
    val timeMinutes: Int,
    val warmth: Float,
    val dimming: Float,
) {
    init {
        require(timeMinutes in 0..1439) {
            "timeMinutes must be in 0..1439, was $timeMinutes"
        }
        require(warmth in 0.0f..1.0f) {
            "warmth must be in 0.0..1.0, was $warmth"
        }
        require(dimming in 0.0f..1.0f) {
            "dimming must be in 0.0..1.0, was $dimming"
        }
    }
}
